---
- name: Get Workloads parent folder
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/api/vcenter/folder?type=VIRTUAL_MACHINE&names=Workloads"
    method: GET
    headers:
      Content-Type: "application/json"
      vmware-api-session-id: "{{ _ocp4_workload_virt_roadshow_vmware_token }}"
    validate_certs: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation | bool }}"
  register: r_parent_folder

- name: Set parent folder ID
  ansible.builtin.set_fact:
    _ocp4_workload_virt_roadshow_vmware_parent_folder_id: "{{ r_parent_folder.json[0].folder }}"

- name: Check if subfolder already exists
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/api/vcenter/folder?type=VIRTUAL_MACHINE&names={{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder }}&parent_folders={{ _ocp4_workload_virt_roadshow_vmware_parent_folder_id }}"
    method: GET
    headers:
      Content-Type: "application/json"
      vmware-api-session-id: "{{ _ocp4_workload_virt_roadshow_vmware_token }}"
    validate_certs: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation | bool }}"
  register: r_existing_folder

- name: Create subfolder in vCenter
  when: r_existing_folder.json | length == 0
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/api/vcenter/folder"
    method: POST
    headers:
      Content-Type: "application/json"
      vmware-api-session-id: "{{ _ocp4_workload_virt_roadshow_vmware_token }}"
    body_format: json
    body:
      name: "{{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder }}"
      parent_folder: "{{ _ocp4_workload_virt_roadshow_vmware_parent_folder_id }}"
    validate_certs: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation | bool }}"
    status_code: 201
  register: r_create_folder
  retries: 10
  delay: 15
  until: r_create_folder is success

- name: Get folder information
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/api/vcenter/folder?type=VIRTUAL_MACHINE&names={{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder }}&parent_folders={{ _ocp4_workload_virt_roadshow_vmware_parent_folder_id }}"
    method: GET
    headers:
      Content-Type: "application/json"
      vmware-api-session-id: "{{ _ocp4_workload_virt_roadshow_vmware_token }}"
    validate_certs: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation | bool }}"
  register: r_folder_info

- name: Set folder ID fact
  ansible.builtin.set_fact:
    _ocp4_workload_virt_roadshow_vmware_vcenter_folder_id: "{{ r_folder_info.json[0].folder }}"

- name: Create VMs
  environment:
    VMWARE_HOST: "{{ vcenter_hostname }}"
    VMWARE_USER: "{{ vcenter_username }}"
    VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_VALIDATE_CERTS: "{{ ocp4_workload_virt_roadshow_vmware_enable_cert_validation }}"
  vmware.vmware_rest.vcenter_vmtemplate_libraryitems:
    name: "{{ vm.name }}{{ _ocp4_workload_virt_roadshow_vmware_vcenter_vmname_suffix }}"
    library: '{{ _ocp4_workload_virt_roadshow_vmware_template_library_id }}'
    template_library_item: "{{ (_ocp4_workload_virt_roadshow_vmware_templates | selectattr('name', 'equalto', vm.template + '-l') | first).id }}"
    placement:
      cluster: "{{ _ocp4_workload_virt_roadshow_vmware_vcenter_cluster_id }}"
      folder: "{{ _ocp4_workload_virt_roadshow_vmware_vcenter_folder_id }}"
    disk_storage:
      datastore: "{{ _ocp4_workload_virt_roadshow_vmware_datastore_id }}"
    state: deploy
    powered_on: false
  retries: 5
  delay: 10
  until: r_vmc_instance is success
  loop: "{{ ocp4_workload_virt_roadshow_vmware_vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  register: r_vmc_instance
